name: Release BTTInstrumentor

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build universal binary
        run: |
          swift build -c release --product BTTInstrumentor \
            --arch arm64 --arch x86_64

          lipo -create \
            .build/arm64-apple-macosx/release/BTTInstrumentor \
            .build/x86_64-apple-macosx/release/BTTInstrumentor \
            -output BTTInstrumentor

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: BTTInstrumentor
